### PR TITLE
Update readme with text for installing on m1 macs

### PR DESCRIPTION
**Pull request by brian-penguin**

### CODE REVIEW

**Comment by joshuaclayton** [comment]
@brimatteng I'm wondering if we should instead default to the Rust allocator and have people opt-in. That way, OOTB it'll work both on Intel and Apple Silicon. The perf bump is nice, but on the majority of projects should be sub-5s on new-ish hardware anyways. What do you think?

**Comment by brian-penguin** [comment]
It's probably better to pass a flag and have it "work" by default, I didn't notice that much real difference in build time between the two branches

**Comment by joshuaclayton** [comment]
@brimatteng I've attempted to address this indirectly by [updating our Homebrew formula to opt-in to MiMalloc here](https://github.com/thoughtbot/homebrew-formulae/pull/73).

**Comment by joshuaclayton** [comment]
@brimatteng I've merged the update to our Homebrew formula, so the stock `brew install complexity` should now work regardless of architecture.

I'm thinking that we can close this without merging, but will leave that to you to confirm. Thanks for flagging!

**Comment by brian-penguin** [comment]
I'm good with closing it. Thanks for updating

**Pull request closed without merging**
